USE employee_db;

insert into departments (dept_name)                                                 values ("Web Dev");
insert into departments (dept_name)                                                 values ("Sales");
insert into roles       (role_title,role_salary,role_manager,dept_id)               values ("VP Engineering",140000.00,1,1);
insert into roles       (role_title,role_salary,role_manager,dept_id)               values ("WebDev Manager",120000.00,1,1);
insert into roles       (role_title,role_salary,role_manager,dept_id)               values ("Lead Engineer" ,100000.00,0,1);
insert into roles       (role_title,role_salary,role_manager,dept_id)               values ("Sr. Engineer"  , 80000.00,0,1);
insert into roles       (role_title,role_salary,role_manager,dept_id)               values ("Jr. Engineer"  , 40000.00,0,1);
insert into roles       (role_title,role_salary,role_manager,dept_id)               values ("VP Sales"      ,140000.00,1,2);
insert into roles       (role_title,role_salary,role_manager,dept_id)               values ("Sales Mgr"     , 80000.00,1,2);
insert into roles       (role_title,role_salary,role_manager,dept_id)               values ("Sales Eng. 2"  , 75000.00,0,2);
insert into roles       (role_title,role_salary,role_manager,dept_id)               values ("Sales Eng. 1"  , 65000.00,0,2);
insert into roles       (role_title,role_salary,role_manager,dept_id)               values ("Sales Admin"   , 40000.00,0,2);
insert into employees   (emp_lastname,emp_firstname,role_id,emp_mgr_id,emp_manager) values ("Fixya","Ican"        , 1,null,1);
insert into employees   (emp_lastname,emp_firstname,role_id,emp_mgr_id,emp_manager) values ("Boss","Pointy-haired", 2,1,1);
insert into employees   (emp_lastname,emp_firstname,role_id,emp_mgr_id,emp_manager) values ("Groundloop","Dilbert", 3,2,0);
insert into employees   (emp_lastname,emp_firstname,role_id,emp_mgr_id,emp_manager) values ("Worthless","Wally"   , 4,2,0);
insert into employees   (emp_lastname,emp_firstname,role_id,emp_mgr_id,emp_manager) values ("Frustrated","Alice"  , 4,2,0);
insert into employees   (emp_lastname,emp_firstname,role_id,emp_mgr_id,emp_manager) values ("Foreign","Asok"      , 5,2,0);
insert into employees   (emp_lastname,emp_firstname,role_id,emp_mgr_id,emp_manager) values ("Sellya","Iwill"      , 6,null,1);
insert into employees   (emp_lastname,emp_firstname,role_id,emp_mgr_id,emp_manager) values ("Quota","Getyer"      , 7,7,1);
insert into employees   (emp_lastname,emp_firstname,role_id,emp_mgr_id,emp_manager) values ("Finesse","Smooth"    , 8,8,0);
insert into employees   (emp_lastname,emp_firstname,role_id,emp_mgr_id,emp_manager) values ("Closer","Hard"       , 8,8,0);
insert into employees   (emp_lastname,emp_firstname,role_id,emp_mgr_id,emp_manager) values ("Happy","Perky"       , 9,8,0);
insert into employees   (emp_lastname,emp_firstname,role_id,emp_mgr_id,emp_manager) values ("Control","Under"     ,10,8,0);
